(() => {
  "use strict";
  const { registerTool, $, escapeHtml, copyText, download, formatBytes, loadScript } = Toolbox;

  registerTool({ id:"pdf", icon:"PDF", name:"PDF 合并 / 拆分", category:"文件", desc:"合并多个 PDF，或提取指定页码。", keywords:"pdf 合并 拆分 提取 页面 文件" }, root => {
    root.innerHTML = `<div class="editor-stack"><div class="inline-note">PDF 在浏览器本地读取和生成；首次使用会加载 pdf-lib。</div><div class="field"><label>合并多个 PDF</label><input id="pdfFiles" class="file-drop" type="file" accept="application/pdf" multiple><div id="pdfList" class="file-list"></div></div><button id="mergePdf" class="primary-btn" type="button">合并并下载</button><hr class="divider"><div class="field"><label>拆分 / 提取页码</label><input id="splitPdfFile" class="file-drop" type="file" accept="application/pdf"></div><div class="two-col"><div class="field"><label>页码，例如 1-3,5</label><input id="pdfPages" class="text-input" placeholder="1-3,5"></div><div class="field"><label>文件名</label><input id="pdfName" class="text-input" value="extracted.pdf"></div></div><button id="splitPdf" class="secondary-btn" type="button">提取并下载</button><div class="output-panel">选择 PDF 后开始处理。</div></div>`;
    const out = $(".output-panel", root), files = $("#pdfFiles", root), list = $("#pdfList", root);
    const ensure = async () => { out.textContent = "正在加载 PDF 组件…"; await loadScript("https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js", () => window.PDFLib); };
    files.onchange = () => { list.innerHTML = [...files.files].map(f => `<div class="file-item"><span>${escapeHtml(f.name)}</span><span>${formatBytes(f.size)}</span></div>`).join(""); };
    $("#mergePdf", root).onclick = async () => { try { if (!files.files.length) throw new Error("请先选择 PDF"); await ensure(); const merged=await PDFLib.PDFDocument.create(); for (const f of files.files) { const src=await PDFLib.PDFDocument.load(await f.arrayBuffer()); (await merged.copyPages(src,src.getPageIndices())).forEach(p=>merged.addPage(p)); } download(new Blob([await merged.save()],{type:"application/pdf"}),"merged.pdf"); out.textContent=`✓ 已合并 ${files.files.length} 个 PDF，共 ${merged.getPageCount()} 页。`; } catch(e) { out.textContent=`错误：${e.message}`; } };
    $("#splitPdf", root).onclick = async () => { try { const f=$("#splitPdfFile",root).files[0]; if(!f) throw new Error("请选择一个 PDF"); await ensure(); const src=await PDFLib.PDFDocument.load(await f.arrayBuffer()), max=src.getPageCount(), set=new Set(); for(const part of $("#pdfPages",root).value.split(",")){ if(part.includes("-")){ let[a,b]=part.split("-").map(Number); if(a>b)[a,b]=[b,a]; for(let i=a;i<=b;i++)set.add(i); } else set.add(Number(part)); } const idx=[...set].filter(n=>Number.isInteger(n)&&n>=1&&n<=max).sort((a,b)=>a-b).map(n=>n-1); if(!idx.length) throw new Error(`请输入 1-${max} 内的页码`); const dest=await PDFLib.PDFDocument.create(); (await dest.copyPages(src,idx)).forEach(p=>dest.addPage(p)); download(new Blob([await dest.save()],{type:"application/pdf"}),$("#pdfName",root).value.trim()||"extracted.pdf"); out.textContent=`✓ 已提取 ${idx.length} 页。`; } catch(e) { out.textContent=`错误：${e.message}`; } };
  });

  registerTool({ id:"image", icon:"▧", name:"图片压缩 / 缩放", category:"图片", desc:"调整尺寸、质量和输出格式。", keywords:"图片 压缩 缩放 jpg png webp 格式 转换" }, root => {
    root.innerHTML = `<div class="editor-stack"><div class="field"><label>选择图片</label><input id="imgFile" class="file-drop" type="file" accept="image/*"></div><div class="three-col"><div class="field"><label>最大宽度 px</label><input id="imgWidth" class="text-input" type="number" min="0" value="1600"></div><div class="field"><label>质量</label><input id="imgQuality" class="text-input" type="number" min="10" max="100" value="82"></div><div class="field"><label>格式</label><select id="imgFormat" class="select-input"><option value="image/webp">WebP</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></div></div><div class="toolbar"><button id="processImage" class="primary-btn" type="button">压缩并预览</button><button id="downloadImage" class="secondary-btn" type="button" disabled>下载图片</button></div><div class="canvas-wrap"><span class="help-text">图片预览</span></div><div class="output-panel">尚未处理。</div></div>`;
    let blob=null, ext="webp";
    const wrap=$(".canvas-wrap",root), out=$(".output-panel",root), dl=$("#downloadImage",root);
    $("#processImage",root).onclick=async()=>{ try { const f=$("#imgFile",root).files[0]; if(!f) throw new Error("请选择图片"); const img=new Image(), url=URL.createObjectURL(f); await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;}); let w=img.naturalWidth,h=img.naturalHeight,max=Number($("#imgWidth",root).value)||0; if(max&&w>max){h=Math.round(h*max/w);w=max;} const c=document.createElement("canvas"); c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);URL.revokeObjectURL(url); const type=$("#imgFormat",root).value,q=Math.min(1,Math.max(.1,(Number($("#imgQuality",root).value)||82)/100)); blob=await new Promise(resolve=>c.toBlob(resolve,type,q)); if(!blob)throw new Error("浏览器不支持该格式"); ext=type.split("/")[1].replace("jpeg","jpg"); wrap.innerHTML="";wrap.appendChild(c);out.textContent=`原图：${img.naturalWidth}×${img.naturalHeight} · ${formatBytes(f.size)}\n输出：${w}×${h} · ${formatBytes(blob.size)}`;dl.disabled=false; } catch(e) { out.textContent=`错误：${e.message}`; } };
    dl.onclick=()=>blob&&download(blob,`toolbox-image.${ext}`);
  });

  registerTool({ id:"ocr", icon:"识", name:"图片 OCR 识字", category:"图片", desc:"从截图、照片或扫描图提取文字。", keywords:"ocr 截图 识字 图片 转文字 扫描" }, root => {
    root.innerHTML = `<div class="editor-stack"><div class="inline-note">首次使用需下载 OCR 引擎与语言模型；识别过程在浏览器中完成。</div><div class="two-col"><div class="field"><label>图片</label><input id="ocrFile" class="file-drop" type="file" accept="image/*"></div><div class="field"><label>语言</label><select id="ocrLang" class="select-input"><option value="chi_sim+eng">简体中文 + 英文</option><option value="eng">英文</option><option value="jpn+eng">日文 + 英文</option></select></div></div><div class="toolbar"><button id="ocrStart" class="primary-btn" type="button">开始识别</button><button id="ocrCopy" class="secondary-btn" type="button">复制</button></div><div class="progress"><span></span></div><div class="output-panel">选择图片开始识别。</div></div>`;
    const out=$(".output-panel",root), bar=$(".progress span",root);
    $("#ocrStart",root).onclick=async()=>{ let worker; try { const f=$("#ocrFile",root).files[0]; if(!f)throw new Error("请选择图片"); out.textContent="正在加载 OCR…"; await loadScript("https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js",()=>window.Tesseract); worker=await Tesseract.createWorker($("#ocrLang",root).value,1,{logger:m=>{if(m.progress!=null)bar.style.width=`${Math.round(m.progress*100)}%`;if(m.status)out.textContent=`${m.status}${m.progress!=null?` ${Math.round(m.progress*100)}%`:""}`;}}); const {data:{text}}=await worker.recognize(f);out.textContent=text.trim()||"未识别到文字";bar.style.width="100%"; } catch(e) { out.textContent=`错误：${e.message}`;bar.style.width="0%"; } finally { if(worker) await worker.terminate(); } };
    $("#ocrCopy",root).onclick=()=>copyText(out.textContent);
  });

  registerTool({ id:"qr", icon:"▦", name:"二维码生成 / 识别", category:"图片", desc:"生成二维码，或识别本地二维码图片。", keywords:"二维码 qr code 生成 识别 链接" }, root => {
    root.innerHTML = `<div class="two-col"><div class="editor-stack"><div class="field"><label>生成二维码</label><textarea id="qrText" class="input-area short-area" placeholder="输入网址或文字"></textarea></div><div class="toolbar"><button id="qrMake" class="primary-btn" type="button">生成</button><button id="qrDownload" class="secondary-btn" type="button" disabled>下载 PNG</button></div><div id="qrCanvasWrap" class="canvas-wrap"><span class="help-text">二维码预览</span></div></div><div class="editor-stack"><div class="field"><label>识别二维码图片</label><input id="qrFile" class="file-drop" type="file" accept="image/*"></div><button id="qrRead" class="secondary-btn" type="button">识别图片</button><div id="qrResult" class="output-panel">识别结果会显示在这里。</div></div></div>`;
    let qrNode=null;
    const wrap=$("#qrCanvasWrap",root), dl=$("#qrDownload",root), result=$("#qrResult",root);
    $("#qrMake",root).onclick=async()=>{ try { const text=$("#qrText",root).value.trim(); if(!text)throw new Error("请输入内容"); await loadScript("https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js",()=>window.QRCode);wrap.innerHTML="";new QRCode(wrap,{text,width:280,height:280,correctLevel:QRCode.CorrectLevel.M}); qrNode=$("canvas",wrap)||$("img",wrap); dl.disabled=!qrNode; } catch(e) { wrap.textContent=`错误：${e.message}`; } };
    dl.onclick=async()=>{ if(!qrNode)return; if(qrNode.tagName==="CANVAS")qrNode.toBlob(blob=>blob&&download(blob,"qrcode.png")); else { const blob=await (await fetch(qrNode.src)).blob();download(blob,"qrcode.png"); } };
    $("#qrRead",root).onclick=async()=>{ try { const f=$("#qrFile",root).files[0];if(!f)throw new Error("请选择二维码图片");await loadScript("https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js",()=>window.jsQR);const bmp=await createImageBitmap(f),c=document.createElement("canvas");c.width=bmp.width;c.height=bmp.height;const ctx=c.getContext("2d",{willReadFrequently:true});ctx.drawImage(bmp,0,0);const d=ctx.getImageData(0,0,c.width,c.height),code=jsQR(d.data,d.width,d.height);result.textContent=code?code.data:"未识别到二维码";bmp.close?.(); } catch(e) { result.textContent=`错误：${e.message}`; } };
  });
})();